CREATE SEQUENCE seq_patient_id START WITH 10 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_doctor_id START WITH 110 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_schedule_id START WITH 2001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_appointment_id START WITH 5001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_visit_id START WITH 9001 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMIT;
